routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

//Before authentication
Route::group(['middleware' => 'beforeAuth'], function() {
    Route::get('/', 'FrontendController@index');
//    Route::get('/', 'Admin\UsersController@login');
    Route::get('page/{type?}', 'FrontendController@index')->name('front');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');
    Route::get('view-service/{id}', 'FrontendController@service')->name('view-service');
    Route::get('service-detail/{id}', 'FrontendController@serviceDetails')->name('service-details');
    Route::get('privacy-policy', 'FooterController@privacy');
    Route::get('terms-conditions', 'FooterController@terms');

    Route::get('view-service-detail/{id}', 'FrontendController@serviceDetail')->name('view-service-detail');

    Route::post('dologin', 'Admin\UsersController@login');
    Route::post('send-message', 'FrontendController@sendMessage')->name('sendMessage');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');


//    Route::post('changePassword', 'Admin\UsersController@changePassword');
    Route::get('gallery/{slug}', 'FrontendController@gallery');
    Route::get('contact', 'FrontendController@contact');
    Route::get('find-your-school', 'FrontendController@findYourSchool');
    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    
    Route::get('frontend/school-details/{id}', 'FrontendController@schoolDetails');
    Route::get('frontend/class-details/{id}', 'FrontendController@classDetails');

    Route::get('parentlogin', 'FrontendController@login');
    Route::get('update-cart/{id?}', 'FrontendController@updateCart');
    Route::get('checkout', 'FrontendController@checkout');
    Route::post('store-order', 'FrontendController@storeOrder');
    Route::match(['get', 'post'], 'view-cart', 'FrontendController@viewCart');
    Route::get('forgotPassword', 'Admin\UsersController@recoverParentPassword');
    Route::get('resetPassword/{token}', 'Admin\UsersController@resetParentPassword');
});
Route::post('changePassword', 'Admin\UsersController@changePassword');


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function() {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list/{role_id?}', 'Admin\UsersController@index')->name('users.index');
    Route::match(['get', 'post'], '/parent-list/{role_id?}', 'Admin\UsersController@parentlist')->name('users.parentlist');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');


    //for home page banner
    // Route::resource('banners', 'BannerController')->except('show');

    Route::get('banners/{type?}', 'BannerController@index')->name('banners.index');
    Route::post('banners/store', 'BannerController@store')->name('banners.store');
    Route::delete('banners/destroy/{id}', 'BannerController@destroy')->name('banners.destroy');

    Route::post('bannar_ajax_upload', 'BannerController@bannar_ajax_upload')->name('bannar_ajax_upload');
    Route::post('banners/sort-order', 'BannerController@sortData')->name('banner.sort.order');
    Route::post('banners-upload', 'TrendingProductController@upload')->name('upload.widget.image');
    Route::get('change-status/{table}/{id}/{status}', 'BannerController@changeStatus')->name('admin.banner.change.status');

    Route::resource('pages', 'PagesController')->except('show');
    Route::get('page-details/{pageId}', 'PagesController@pageDetails')->name('page.details');
    Route::get('contact-details/{pageId}', 'PagesController@contactDetails')->name('contact.details');
    Route::get('pages/edit/{id?}', 'PagesController@index');
    Route::get('page-details/create/{pageId}', 'PagesController@pageDetailCreate')->name('page.details.create');
    Route::post('page-details/store/{pageId}', 'PagesController@pageDetailStore')->name('page.details.store');
    Route::get('page-details/edit/{id}', 'PagesController@pageDetailEdit')->name('page.details.edit');
    Route::put('page-details/update/{id}', 'PagesController@pageDetailUpdate')->name('page.details.update');

    Route::post('categories/store', 'GalleriesController@categoriesStore')->name('categories.store');
    Route::get('categories', 'GalleriesController@categories')->name('categories.index');
    Route::get('categories/edit/{id}', 'GalleriesController@categoriesEdit')->name('categories.edit');
    Route::get('categories/create', 'GalleriesController@categoriesCreate')->name('categories.create');
    Route::put('categories/update/{id}', 'GalleriesController@categoriesUpdate')->name('categories.update');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('demand-liberaries/create', 'DemandLiberariesController@create')->name('demand_liberaries.create');
    Route::post('demand-liberaries/store', 'DemandLiberariesController@store')->name('demand_liberaries.store');
    Route::get('demand-liberaries/edit/{id}', 'DemandLiberariesController@edit')->name('demand_liberaries.edit');
    Route::put('demand-liberaries/update/{id}', 'DemandLiberariesController@update')->name('demand_liberaries.update');
    Route::delete('demand-liberaries/destroy/{id}', 'DemandLiberariesController@destroy')->name('demand.destroy');
    

    Route::get('galleries/{id}', 'GalleriesController@index')->name('galleries');
    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');
    Route::delete('galleries/destroy/{id}', 'GalleriesController@destroy')->name('galleries.destroy');
    Route::post('ck-editor/uploads', 'BannerController@ckeditorUpload')->name('ckeditor.upload');

    Route::delete('category/destroy/{id}', 'GalleriesController@destroyCategory')->name('category.destroy');
    Route::delete('page_details/destroy/{id}', 'PagesController@pageDetailDestroy')->name('page_details.destroy');
//    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');

    Route::get('contacts', 'PagesController@contacts');
    Route::delete('contacts/destroy/{id}', 'PagesController@ContactsDestroy')->name('contact.destroy');

    Route::post('pages/updatetype', 'PagesController@updateType')->name('pages.updatetype');
    Route::get('services/{type?}', 'ServicesController@index')->name('services.index');
    Route::post('services/store', 'ServicesController@store')->name('services.store');
    Route::delete('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');

    Route::resource('testimonials', 'TestimonialController');
    Route::resource('teams', 'TeamController');

    Route::resource('footers', 'FooterController');

    Route::match(['get', 'post'], 'states', 'Admin\StatesController@index');
    Route::get('states/create/{id?}', 'Admin\StatesController@create');
    Route::post('states/store', 'Admin\StatesController@store')->name('states.store');
    Route::delete('states-destroy/{id}', 'Admin\StatesController@destroy')->name('states.destroy');

    Route::match(['get', 'post'], 'cities/{state_id}', 'Admin\CitiesController@index');
    Route::get('cities-create/{state_code}/{id?}', 'Admin\CitiesController@create');
    Route::post('cities-store', 'Admin\CitiesController@store')->name('cities.store');
    Route::delete('cities-destroy/{id}', 'Admin\CitiesController@destroy')->name('cities.destroy');



    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::get('schools-create/{id?}', 'Admin\SchoolsController@create');
    Route::post('schools-store', 'Admin\SchoolsController@store')->name('schools.store');
    Route::delete('schools-destroy/{id}', 'Admin\SchoolsController@destroy')->name('schools.destroy');


    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    Route::get('class-dd', 'AdmissionsController@classDD')->name('class-dd');
    Route::get('child-dd', 'AdmissionsController@childDD')->name('child-dd');


    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::get('school-classes-create/{school_id}/{class_id?}', 'Admin\SchoolClassesController@create');
    Route::post('school-classes-store', 'Admin\SchoolClassesController@store')->name('school.classes.store');
    Route::delete('schools-classes-destroy/{id}', 'Admin\SchoolClassesController@destroy')->name('schools.classes.destroy');


    Route::get('admissions', 'AdmissionsController@index');

resources/views/footer.blade.php
<div class="ajax-loader" style="background:white;display:none;padding:10px;">
    <img src="{{asset('img/loading.gif')}}" style="display:block;margin:auto;" />
</div>

</div>
<!-- End of Content Container -->
</div>
<!-- END PAGE CONTENT -->
<!-- START COPYRIGHT -->
<!-- START CONTAINER FLUID -->
<!-- START CONTAINER FLUID -->
<div class=" container   container-fixed-lg footer">
    <div class="copyright sm-text-center">
        <p class="small no-margin pull-left sm-pull-reset">
            <span class="hint-text">Copyright &copy; {{@date('Y')}} </span>
            <span class="font-montserrat">{{config('app.name','Content Management System')}}</span>.
            <span class="hint-text">All rights reserved. </span>
        </p>
        {{--<p class="small no-margin pull-right sm-pull-reset">
            <a href="https://www.cyberclouds.com">Cyber Clouds</a> <span class="hint-text"> made with Love</span>
              </p>--}}
        <div class="clearfix"></div>
    </div>
</div>
<!-- END COPYRIGHT -->
</div>
<!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTAINER -->

resources/views/header.blade.php
<div class="header p-r-0" style="background: linear-gradient(to right, #eee 10%,#1e3143);">
    <div class="header-inner" style="height: 90px">
        <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-menu text-white" data-toggle="horizontal-menu"></a>
        <div class="">
            <div class="brand inline no-border d-sm-inline-block">
                <img style="width: 160px;" src="{{asset('public/frontend/images/logo/techie_kids_logo.png')}}" 
                     alt="{{config('app.name')}}" 
                     data-src="{{asset('public/frontend/images/logo/techie_kids_logo.png')}}" 
                     data-src-retina="{{asset('public/frontend/images/logo/techie_kids_logo.png')}}" class="img-fluid">
            </div>
        </div>
        <div class="d-flex align-items-center">
            <!-- START User Info-->

            <div class="dropdown pull-right">
                <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="pull-left p-r-10 fs-14 font-heading d-lg-inline-block text-white">
                        <span class="semi-bold">{{Auth::user()->first_name}} {{Auth::user()->last_name}}</span>
                    </div>
                </button>
                <?php
                $user = Auth::user();
                $role = $user->ModelHasRoles->pluck('role_id')->toArray();
                ?>
                @if(in_array(2,$role))
                <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                    <!-- <a href="{{url('/backend/user-profile')}}" class="dropdown-item"><i class="fa fa-user"></i> Profile</a> -->
                    <a href="{{url('/')}}/teacher/change-password" class="dropdown-item"><i class="pg-settings_small"></i> Change Password</a>
                    <a href="javascript:" onClick="event.preventDefault();document.getElementById('logout-form').submit()" class="clearfix bg-master-lighter dropdown-item">
                        <form action="{{route('teacher.logout')}}" method="POST" style="display:none;" id="logout-form">
                            @csrf
                            @method('POST')
                        </form>
                        <span class="pull-left">Logout</span>
                        <span class="pull-right"><i class="pg-power"></i></span>
                    </a>
                </div>
                @else
                <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                    <!-- <a href="{{url('/backend/user-profile')}}" class="dropdown-item"><i class="fa fa-user"></i> Profile</a> -->
                    <a href="{{url('/')}}/backend/change-password" class="dropdown-item"><i class="pg-settings_small"></i> Change Password</a>
                    <a href="javascript:" onClick="event.preventDefault();document.getElementById('logout-form').submit()" class="clearfix bg-master-lighter dropdown-item">
                        <form action="{{route('admin.logout')}}" method="POST" style="display:none;" id="logout-form">
                            @csrf
                            @method('POST')
                        </form>
                        <span class="pull-left">Logout</span>
                        <span class="pull-right"><i class="pg-power"></i></span>
                    </a>
                </div>
                @endif
            </div>
            <!-- END User Info-->
        </div>
    </div>
    @auth
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="">
                <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-close" data-toggle="horizontal-menu"></a>

                @if(in_array(2,$role))
                <ul>
                    <li class="@if(in_array('dashboard',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/dashboard">Dashboard</a>
                    </li>
                    <li class="@if(in_array('schools',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/teacher/schools">Schools</a>
                    </li>                    
                    <li class="@if(in_array('demand-liberaries',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/teacher/demand-liberaries">Demand Library</a>
                    </li>

                    <li class="@if(in_array('reports',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/teacher/reports/search-all">Search</a>
                    </li>
                </ul>
                @else
                <ul>
                    <li class="@if(in_array('dashboard',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/dashboard">Dashboard</a>
                    </li>
                    @canany(['user-list','role-list'])
                    <li class="@if(in_array('users',Request::segments()) || in_array('users-list',Request::segments()) || in_array('roles',Request::segments())) {{'active'}} @endif">
                        <a class="nav-link dropdown-toggle"
                           id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                           href="javascript:">Users</a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                            @can('user-list')
                            <a class="nav-link" href="{{ route('admin.users.index') }}">Manage Users</a>
                            @endcan
                            @can('role-list')
                            <a class="nav-link" href="{{ route('admin.roles.index') }}">Manage Roles</a>
                            @endcan
                        </div>
                    </li> 
                    @endcanany

                    @canany(['user-list','role-list'])
                    <li class="@if(in_array('children',Request::segments()) || in_array('parent-list',Request::segments())) {{'active'}} @endif">
                        <a href="{{ route('admin.users.parentlist') }}">Parents</a>

                    </li> 
                    @endcanany

                    @can('banner-list')
                    <li class="@if(in_array('banners',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/banners">Banners</a>
                    </li>
                    @endcan
                    @can('page-list')
                    <li class="@if(in_array('pages',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/pages">Pages</a>
                    </li>
                    @endcan
                    @can('testimonials-list')
                    <li class="@if(in_array('teams',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/teams">Team</a>
                    </li>
                    <li class="@if(in_array('testimonials',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/testimonials">Testimonial</a>
                    </li>
                    @endcan
                    @can('gallery-list')
                    <li class="@if(in_array('categories',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/categories">Gallery</a>
                    </li> 
                    @endcan

                    @can('schools-list')
                    <li class="@if(in_array('schools',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/schools">Schools</a>
                    </li>                    
                    @endcan                    
                    @can('admissions-list')
                    <li class="@if(in_array('admissions',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/backend/admissions')}}">Admissions</a>
                    </li>    
                    @endcan
                    @can('faq-list')
                    <li class="@if(in_array('questions',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/questions">FAQ</a>
                    </li>
                    @endcan

                    <li class="@if(in_array('reports',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/reports/search-all">Search</a>
                    </li>
                    @can('setting-list')
                    <li class="@if(in_array('contacts',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/contacts">Contacts</a>
                    </li>
                    <li class="@if(in_array('footers',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/footers">Site Detail</a>
                    </li>
                    @endcan
                    @can('states-list')
                    <li class="@if(in_array('states',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/states">States</a>
                    </li>
                    @endcan
                    @can('demand-liberaries-list')
                    <li class="@if(in_array('demand-liberaries',Request::segments())) {{'active'}} @endif">
                        <a href="{{url('/')}}/backend/demand-liberaries">Demand Library</a>
                    </li>
                    @endcan
                </ul>

                @endif
            </div>
        </div>
    </div>
    @endauth
</div>

<div class="page-container ">
    <!-- START PAGE CONTENT WRAPPER -->
    <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content sm-gutter">
            <!-- START BREADCRUMBS -->
            <div class="bg-white">
                <div class="container">

                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item"><a href="{{url('/')}}/backend/dashboard">Home</a></li>
                        <?php
                        $link = URL::to('/');
                        $allSegments = Request::segments();
                        // dd($allSegments);
                        ?>
                        @for($i = 1; $i <= count(Request::segments()); $i++)
                        @if($i < count(Request::segments()) & $i > 0)
                        <?php
                        if (Request::segment($i) == 'edit') {
                            continue;
                        }
                        if (is_numeric(Request::segment($i))) {
                            continue;
                        }

                        $link .= "/" . Request::segment($i);

                        if ($link != URL::to('/') . "/backend") {
                            if ($i != 3 && is_int(intval(ucwords(str_replace('-', ' ', Request::segment($i)))))) {
                                $s2 = str_replace('-', ' ', Request::segment($i));
                                ?>
                                <li class="breadcrumb-item"><a href="<?= $link ?>">{{ ucwords($s2)}}</a> </li>
                                <?php
                            }
                        }
                        ?>
                        @else  
                        <?php
                        $s2 = str_replace('_', ' ', str_replace('-', ' ', Request::segment($i)));
                        ?>
                        <li class="breadcrumb-item active"> {{  ucwords($s2) }}</li>
                        @endif
                        @endfor  
                    </ol>
                </div>
            </div>
            <!-- END BREADCRUMBS -->
            <div class="container sm-padding-10 p-t-20 p-l-0 p-r-0">
                @include('partials.alerts')

resources/views/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <title>{{config('app.name','Content Management System')}} - @yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="{{ asset('pages/css/themes/modern.css') }}" />
    <link rel="stylesheet" href="{{asset('login/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('login/css/animate.css')}}">
    <link rel="stylesheet" href="{{ asset('validate-password/css/jquery.passwordRequirements.css') }}" />
    </head>
     <!--style="background-image: url(<?=asset('login/images/gps-login.jpg')?>);overflow:hidden;"-->
    <body class="img js-fullheight">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-0" style="background: rgba(255,255,255,0.8);padding: 10px;">
                    <h2 class="heading-section">
                        <img src="{{asset('public/frontend/images/logo/techie_kids_logo.png')}}" width="280px"/></h2>
                </div>
            </div>
             @yield('content')
            
        </div>
    </section>

    <script src="{{asset('login/js/jquery.min.js')}}"></script>
  <script src="{{asset('login/js/popper.js')}}"></script>
  <script src="{{asset('login/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('login/js/main.js')}}"></script>
   <script src="{{asset('plugins/jquery-validation/js/jquery.validate.min.js')}}" type="text/javascript"></script>
        <!-- END VENDOR JS -->
        <script src="{{ asset('validate-password/js/jquery.passwordRequirements.js') }}"></script>

        <script src="{{asset('pages/js/pages.min.js')}}"></script>
        <script>
function redMustEmpty() {
    if ($('#redField').val().length > 0) {
        return false;
    }
}
$(function ()
{
    $(".pr-password").passwordRequirements();
    $('#form-login').validate({
        rules: {
            email: {
                required: true,
                email: true
            },
            password: {
                required: true,
                minlength: 8
            },
            red_box: {
                maxlength: 0
            },
            green_box: {
                required: true
            }
        },
        messages: {
            red_box: {
                maxlength: 'The red box must be empty'
            }
        },
        submitHandler: function (form) {
            $("#submitForm").html("Please wait...").attr('disabled', true);
            form.submit();
        }

    });





    $('#form-resetpass').validate({
        rules: {
            password: {
                required: true,
                pwcheck: true,
                minlength: 8
            },
            password_confirmation: {
                required: true,
                equalTo: "#password"
            }
        },
        message: {
            password: {
                required: "Password Required",
                pwcheck: "Password Week",
                minlength: "min 8 Char"
            }
        },
        submitHandler: function (form) {
            $("#submitForm").html("Please wait...").attr('disabled', true);
            form.submit();
        }

    });
    $.validator.addMethod("pwcheck", function (value) {

        return /^[a-zA-Z0-9!@#$%^&*()_=\[\]{};':"\\|,.<>\/?+-]+$/.test(value)
                && /[a-z]/.test(value) // has a lowercase letter
                && /\d/.test(value)//has a digit
                && /[!@#$%^&*()_=\[\]{};':"\\|,.<>\/?+-]/.test(value)// has a special character
    }, "Must consist  lowercase letter, number and special characters");

});
        </script>

    </body>
</html>