routes/web.php
Route::post('changePassword', 'Admin\UsersController@changePassword');


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function() {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list/{role_id?}', 'Admin\UsersController@index')->name('users.index');
    Route::match(['get', 'post'], '/parent-list/{role_id?}', 'Admin\UsersController@parentlist')->name('users.parentlist');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');


    //for home page banner
    // Route::resource('banners', 'BannerController')->except('show');

    Route::get('banners/{type?}', 'BannerController@index')->name('banners.index');
    Route::post('banners/store', 'BannerController@store')->name('banners.store');
    Route::delete('banners/destroy/{id}', 'BannerController@destroy')->name('banners.destroy');

    Route::post('bannar_ajax_upload', 'BannerController@bannar_ajax_upload')->name('bannar_ajax_upload');
    Route::post('banners/sort-order', 'BannerController@sortData')->name('banner.sort.order');
    Route::post('banners-upload', 'TrendingProductController@upload')->name('upload.widget.image');
    Route::get('change-status/{table}/{id}/{status}', 'BannerController@changeStatus')->name('admin.banner.change.status');

    Route::resource('pages', 'PagesController')->except('show');
    Route::get('page-details/{pageId}', 'PagesController@pageDetails')->name('page.details');
    Route::get('contact-details/{pageId}', 'PagesController@contactDetails')->name('contact.details');
    Route::get('pages/edit/{id?}', 'PagesController@index');
    Route::get('page-details/create/{pageId}', 'PagesController@pageDetailCreate')->name('page.details.create');
    Route::post('page-details/store/{pageId}', 'PagesController@pageDetailStore')->name('page.details.store');
    Route::get('page-details/edit/{id}', 'PagesController@pageDetailEdit')->name('page.details.edit');
    Route::put('page-details/update/{id}', 'PagesController@pageDetailUpdate')->name('page.details.update');

    Route::post('categories/store', 'GalleriesController@categoriesStore')->name('categories.store');
    Route::get('categories', 'GalleriesController@categories')->name('categories.index');
    Route::get('categories/edit/{id}', 'GalleriesController@categoriesEdit')->name('categories.edit');
    Route::get('categories/create', 'GalleriesController@categoriesCreate')->name('categories.create');
    Route::put('categories/update/{id}', 'GalleriesController@categoriesUpdate')->name('categories.update');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('demand-liberaries/create', 'DemandLiberariesController@create')->name('demand_liberaries.create');
    Route::post('demand-liberaries/store', 'DemandLiberariesController@store')->name('demand_liberaries.store');
    Route::get('demand-liberaries/edit/{id}', 'DemandLiberariesController@edit')->name('demand_liberaries.edit');
    Route::put('demand-liberaries/update/{id}', 'DemandLiberariesController@update')->name('demand_liberaries.update');
    Route::delete('demand-liberaries/destroy/{id}', 'DemandLiberariesController@destroy')->name('demand.destroy');
    

    Route::get('galleries/{id}', 'GalleriesController@index')->name('galleries');
    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');
    Route::delete('galleries/destroy/{id}', 'GalleriesController@destroy')->name('galleries.destroy');
    Route::post('ck-editor/uploads', 'BannerController@ckeditorUpload')->name('ckeditor.upload');

    Route::delete('category/destroy/{id}', 'GalleriesController@destroyCategory')->name('category.destroy');
    Route::delete('page_details/destroy/{id}', 'PagesController@pageDetailDestroy')->name('page_details.destroy');
//    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');

    Route::get('contacts', 'PagesController@contacts');
    Route::delete('contacts/destroy/{id}', 'PagesController@ContactsDestroy')->name('contact.destroy');

    Route::post('pages/updatetype', 'PagesController@updateType')->name('pages.updatetype');
    Route::get('services/{type?}', 'ServicesController@index')->name('services.index');
    Route::post('services/store', 'ServicesController@store')->name('services.store');
    Route::delete('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');

    Route::resource('testimonials', 'TestimonialController');
    Route::resource('teams', 'TeamController');

    Route::resource('footers', 'FooterController');

    Route::match(['get', 'post'], 'states', 'Admin\StatesController@index');
    Route::get('states/create/{id?}', 'Admin\StatesController@create');
    Route::post('states/store', 'Admin\StatesController@store')->name('states.store');
    Route::delete('states-destroy/{id}', 'Admin\StatesController@destroy')->name('states.destroy');

    Route::match(['get', 'post'], 'cities/{state_id}', 'Admin\CitiesController@index');
    Route::get('cities-create/{state_code}/{id?}', 'Admin\CitiesController@create');
    Route::post('cities-store', 'Admin\CitiesController@store')->name('cities.store');
    Route::delete('cities-destroy/{id}', 'Admin\CitiesController@destroy')->name('cities.destroy');



    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::get('schools-create/{id?}', 'Admin\SchoolsController@create');
    Route::post('schools-store', 'Admin\SchoolsController@store')->name('schools.store');
    Route::delete('schools-destroy/{id}', 'Admin\SchoolsController@destroy')->name('schools.destroy');


    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    Route::get('class-dd', 'AdmissionsController@classDD')->name('class-dd');
    Route::get('child-dd', 'AdmissionsController@childDD')->name('child-dd');


    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::get('school-classes-create/{school_id}/{class_id?}', 'Admin\SchoolClassesController@create');
    Route::post('school-classes-store', 'Admin\SchoolClassesController@store')->name('school.classes.store');
    Route::delete('schools-classes-destroy/{id}', 'Admin\SchoolClassesController@destroy')->name('schools.classes.destroy');


    Route::get('admissions', 'AdmissionsController@index');
    Route::post('search_stripe', 'AdmissionsController@search_stripe')->name('admission.search_stripe');
    Route::get('questions/{type?}', 'QuestionsController@index')->name('questions.index');
    Route::post('questions/store', 'QuestionsController@store')->name('questions.store');
    Route::delete('questions/destroy/{id}', 'QuestionsController@destroy')->name('questions.destroy');

    Route::get('reports/search-all', 'Admin\ReportsController@searchAll')->name('reports.index');
    Route::get('dl-file-destroy/{id?}/{file?}', 'DemandLiberariesController@dlFileDestroy')->name('reports.index');
});
Route::get('load-students/{id}', 'Admin\SchoolClassesController@loadStd');

Route::prefix('parent')->name('parent.')->middleware('checkAuth')->group(function() {
    Route::get('dashboard', 'Parent\ParentsController@dashboard');
    Route::get('children/{user_id?}', 'Parent\ParentsController@children');
    Route::get('children-create/{id?}', 'Parent\ParentsController@childCreate');
    Route::post('children/store/{user_id?}', 'Parent\ParentsController@childStore')->name('children.store');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::post('update-profile', 'Parent\ParentsController@updateProfile');
    Route::get('children-delete/{id}', 'Parent\ParentsController@deleteChild');
    Route::get('add-details/{id}', 'Parent\ParentsController@admissionDetails');
    Route::get('demand_library', 'Parent\ParentsController@demandLibrary');

    Route::get('stripesuccess', function () {
        return view('stripesuccess');
    });
    Route::post('stripepay', 'Parent\ParentsController@stripepay');
    Route::get('cancelsubscription/{id}', 'Parent\ParentsController@cancelstripesubscription');
});
Route::post('register-parent', 'Admin\UsersController@store');
Route::prefix('teacher')->name('teacher.')->middleware('checkAuth')->group(function() {
    Route::get('reports/search-all', 'Admin\ReportsController@searchAll')->name('reports.index');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::get('change-password', 'Admin\UsersController@changePassword');
});
Route::get('thanks', 'FrontendController@thanks');
Route::get('get-liberary-details/{id}', 'DemandLiberariesController@getDetail');

Route::get('demo', function () {
    return redirect('/page/schedule-a-demo');
});
Route::get('school-partnerships', function () {
    return redirect('/page/school-partnerships');
});
Route::get('enroll-your-school.html', function () {
    return redirect('/page/schedule-a-demo');
});

Route::get('enrichmentatschool.html', function () {
    return redirect('/page/classes');
});
Route::get('enroll-your-child.html', function () {

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Database\Eloquent\SoftDeletes;


class State extends Model implements Auditable {

    use \OwenIt\Auditing\Auditable,
        SoftDeletes,
        HasFactory;

    protected $guarded = [];

    public function cities() {
        return $this->hasMany(City::class, 'state_code', 'state_code');
    }

    public function scopeGetAll($query) {
        return $query->get();
    }

    public function scopeDropdown($query) {
        return $query->select('id', 'state as value');
    }

    protected static function boot() {
        parent::boot();

        static::creating(function($model) {
            $user = auth()->user();
            $model->created_by = $user->id;
            $model->updated_by = $user->id;
        });

        static::updating(function($model) {
            $user = auth()->user();
            $model->updated_by = $user->id;
        });
    }

}

app/Http/Controllers/Admin/StatesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\State;
use Illuminate\Support\Facades\DB;

class StatesController extends Controller {

    public function index(Request $request) {
        $states = State::paginate(15);
        if ($request->ajax()) {
//            $pageNo = $request->input('page', 1);
//            if ($request->is_fresh_data == 1) {
//                $pageNo = 1;
//            }
            $view = view('admin.states.table', compact('states'))
//                    ->with('i', ($pageNo - 1) * $records)
                    ->render();
            return response()->json(['html' => $view]);
        }
        return view('admin.states.index', compact('states'));
    }

    public function create($id = null) {
        $state = new State();
        if ($id) {
            $state = State::find($id);
        }
        $view = view('admin.states.form', compact('state'))
                ->render();
        return response()->json(['html' => $view]);
    }

    public function store(Request $request) {
        try {
            DB::beginTransaction();

            $state = $request->record;
            $id = $request->id;
//            dd($);
            if ($id) {
                $state['updated_by'] = auth()->user()->id;
                $state = State::find($id)->update($state);
                $outcome = "State Updated Successfully";
            } else {
                $state = State::create($state);
                $outcome = "State Created Successfully";
            }

            DB::commit();
            return redirect()->back()->with('outcome', $outcome);
        } catch (QueryException $e) {
            DB::rollback();
            dd($e);
        }
    }

    public function destroy($id) {

        $outcome = '';
        try {
            DB::beginTransaction();
            $state = State::find($id);

            if ($state->cities->count()) {
                return redirect()->back()->with('error', 'Some cities are associated to this state. Please delete cities first');
            }

            $state->delete();

            $outcome = "State deleted successfully.";

            DB::commit();
        } catch (QueryException $e) {
            DB::rollback();
            dd($e);
        }

        return redirect()->back()->with('outcome', $outcome);
    }

}

resources/views/admin/states/form.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title pull-left">
                    @if(request()->id)
                    {{ __('Edit State') }}
                    @else
                    {{ __('Create State') }}
                    @endif
                </div>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.states.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>State</label>
                            <input value="{{ $state->id }}" type="hidden" class="form-control" name="id"/>
                            <input value="{{ $state->state }}" type="text" class="form-control" name="record[state]"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>State Code</label>
                            <input 
                                @if(request()->id)
                                disabled
                                @endif
                                type="text" value="{{ $state->state_code }}" class="form-control" name="record[state_code]"/>
                        </div>
                    </div>
                    <div class="row">
                    </div>
                    <div class="text-right">
                        <a href="javascript:" onclick="removeForm()" class="mt-2 btn btn-success">Cancel</a>
                        @if(request()->id)
                        <button type="submit" class="mt-2 btn btn-success">Update</button>
                        @else
                        <button type="submit" class="mt-2 btn btn-success">Add</button>
                        @endif
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/states/index.blade.php
@extends('master')
@section('content')
<div class="mb-2">
    <h1 class="float-left">States</h1>
    <div class="clearfix"></div>

    <div class="pull-left">
        <b>Legends: </b>
        <i style="padding: 1px 9px;" data-toggle="tooltip" data-placement="top" title="" class="rounded-circle bg-success ml-2 mr-2" data-original-title="Active"></i>
        <i style="padding: 1px 9px;" class="rounded-circle bg-danger mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Inactive"></i>
    </div>
    @can('states-edit')
    <a onclick="event.preventDefault();loadForm(this)" class="btn btn-success float-right" href="<?= url('backend/states/create') ?>">Create State</a>
    @endcan
    <div class="clearfix"></div>
</div>


<div class="record-form"></div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <!--            <div class="card-header">
                            <div class="card-title pull-left">States</div>
                        </div>-->
            <div class="card-body">
                <div class="row table-responsive" id="no-more-tables">
                    @include('admin.states.table')
                </div>

            </div>
        </div>
    </div>
</div>
@include('partials.loadmorejs')
@endsection
@section('script')
@if(Session::has('outcome'))
<script>
    $(function () {
        $.toaster({priority: 'success', title: 'Success', message: "{{Session::get('outcome')}}"});
    })

</script>
@endif
@endsection

resources/views/admin/states/table.blade.php
<table class="sortable table table-bordered table-small">
    <thead>
        <tr>
            <th>State</th>
            <th>State Code</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($states as $state)
        <tr>
            <td>
                <?= $state->state ?>
            </td>
            <td>
                <?= $state->state_code ?>
            </td>
            <td>               
                @can('states-edit')

                <a href="{{ url('backend/change-status/states/'.$state->id,$state->status) }}">

                    <span class="span-status {{ $state->status == 1 ? 'active-span-bg': 'disabled-span-bg' }}">
                        {{ $state->status == 1 ? __('Active') : __('Blocked') }}
                    </span>
                </a>
                @else
                    <span class="span-status {{ $state->status == 1 ? 'active-span-bg': 'disabled-span-bg' }}">
                        {{ $state->status == 1 ? __('Active') : __('Blocked') }}
                    </span>
                @endcan
            </td>
            <td>
                @can('cities-list')
                <a href="<?= url('backend/cities/' . $state->state_code) ?>"
                   class="btn btn-small btn-sm btn-success">
                    Cities
                </a>
                @endcan
                @can('states-edit')
                <a onclick="event.preventDefault(); loadForm(this)" href="<?= url('backend/states/create/' . $state->id) ?>"
                   class="btn btn-small btn-sm btn-primary">
                    <i class="fa fa-edit"></i>
                </a>
                <button type="submit"
                        onclick="event.preventDefault(); setUrl('{{ route('admin.states.destroy', $state->id) }}'); deleteConfirm('destroy', 'Are you sure?')"
                        class="btn btn-icon btn-round btn-danger btn-small btn-sm">
                    <i class="fa fa-trash"></i>
                </button>
                @endcan
            </td>
        </tr>
        @endforeach

    </tbody>
</table>
<form 
    id="destroy"
    method="post" id="destroy" 
    action="">
    @csrf
    @method('DELETE')
</form>
{{ $states->links() }}