routes/web.php
Route::post('changePassword', 'Admin\UsersController@changePassword');


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function() {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list/{role_id?}', 'Admin\UsersController@index')->name('users.index');
    Route::match(['get', 'post'], '/parent-list/{role_id?}', 'Admin\UsersController@parentlist')->name('users.parentlist');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');


    //for home page banner
    // Route::resource('banners', 'BannerController')->except('show');

    Route::get('banners/{type?}', 'BannerController@index')->name('banners.index');
    Route::post('banners/store', 'BannerController@store')->name('banners.store');
    Route::delete('banners/destroy/{id}', 'BannerController@destroy')->name('banners.destroy');

    Route::post('bannar_ajax_upload', 'BannerController@bannar_ajax_upload')->name('bannar_ajax_upload');
    Route::post('banners/sort-order', 'BannerController@sortData')->name('banner.sort.order');
    Route::post('banners-upload', 'TrendingProductController@upload')->name('upload.widget.image');
    Route::get('change-status/{table}/{id}/{status}', 'BannerController@changeStatus')->name('admin.banner.change.status');

    Route::resource('pages', 'PagesController')->except('show');
    Route::get('page-details/{pageId}', 'PagesController@pageDetails')->name('page.details');
    Route::get('contact-details/{pageId}', 'PagesController@contactDetails')->name('contact.details');
    Route::get('pages/edit/{id?}', 'PagesController@index');
    Route::get('page-details/create/{pageId}', 'PagesController@pageDetailCreate')->name('page.details.create');
    Route::post('page-details/store/{pageId}', 'PagesController@pageDetailStore')->name('page.details.store');
    Route::get('page-details/edit/{id}', 'PagesController@pageDetailEdit')->name('page.details.edit');
    Route::put('page-details/update/{id}', 'PagesController@pageDetailUpdate')->name('page.details.update');

    Route::post('categories/store', 'GalleriesController@categoriesStore')->name('categories.store');
    Route::get('categories', 'GalleriesController@categories')->name('categories.index');
    Route::get('categories/edit/{id}', 'GalleriesController@categoriesEdit')->name('categories.edit');
    Route::get('categories/create', 'GalleriesController@categoriesCreate')->name('categories.create');
    Route::put('categories/update/{id}', 'GalleriesController@categoriesUpdate')->name('categories.update');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('demand-liberaries/create', 'DemandLiberariesController@create')->name('demand_liberaries.create');
    Route::post('demand-liberaries/store', 'DemandLiberariesController@store')->name('demand_liberaries.store');
    Route::get('demand-liberaries/edit/{id}', 'DemandLiberariesController@edit')->name('demand_liberaries.edit');
    Route::put('demand-liberaries/update/{id}', 'DemandLiberariesController@update')->name('demand_liberaries.update');
    Route::delete('demand-liberaries/destroy/{id}', 'DemandLiberariesController@destroy')->name('demand.destroy');
    

    Route::get('galleries/{id}', 'GalleriesController@index')->name('galleries');
    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');
    Route::delete('galleries/destroy/{id}', 'GalleriesController@destroy')->name('galleries.destroy');
    Route::post('ck-editor/uploads', 'BannerController@ckeditorUpload')->name('ckeditor.upload');

    Route::delete('category/destroy/{id}', 'GalleriesController@destroyCategory')->name('category.destroy');
    Route::delete('page_details/destroy/{id}', 'PagesController@pageDetailDestroy')->name('page_details.destroy');
//    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');

    Route::get('contacts', 'PagesController@contacts');
    Route::delete('contacts/destroy/{id}', 'PagesController@ContactsDestroy')->name('contact.destroy');

    Route::post('pages/updatetype', 'PagesController@updateType')->name('pages.updatetype');
    Route::get('services/{type?}', 'ServicesController@index')->name('services.index');
    Route::post('services/store', 'ServicesController@store')->name('services.store');
    Route::delete('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');

    Route::resource('testimonials', 'TestimonialController');
    Route::resource('teams', 'TeamController');

    Route::resource('footers', 'FooterController');

    Route::match(['get', 'post'], 'states', 'Admin\StatesController@index');
    Route::get('states/create/{id?}', 'Admin\StatesController@create');
    Route::post('states/store', 'Admin\StatesController@store')->name('states.store');
    Route::delete('states-destroy/{id}', 'Admin\StatesController@destroy')->name('states.destroy');

    Route::match(['get', 'post'], 'cities/{state_id}', 'Admin\CitiesController@index');
    Route::get('cities-create/{state_code}/{id?}', 'Admin\CitiesController@create');
    Route::post('cities-store', 'Admin\CitiesController@store')->name('cities.store');
    Route::delete('cities-destroy/{id}', 'Admin\CitiesController@destroy')->name('cities.destroy');



    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::get('schools-create/{id?}', 'Admin\SchoolsController@create');
    Route::post('schools-store', 'Admin\SchoolsController@store')->name('schools.store');
    Route::delete('schools-destroy/{id}', 'Admin\SchoolsController@destroy')->name('schools.destroy');


    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    Route::get('class-dd', 'AdmissionsController@classDD')->name('class-dd');
    Route::get('child-dd', 'AdmissionsController@childDD')->name('child-dd');


    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::get('school-classes-create/{school_id}/{class_id?}', 'Admin\SchoolClassesController@create');
    Route::post('school-classes-store', 'Admin\SchoolClassesController@store')->name('school.classes.store');
    Route::delete('schools-classes-destroy/{id}', 'Admin\SchoolClassesController@destroy')->name('schools.classes.destroy');


    Route::get('admissions', 'AdmissionsController@index');
    Route::post('search_stripe', 'AdmissionsController@search_stripe')->name('admission.search_stripe');
    Route::get('questions/{type?}', 'QuestionsController@index')->name('questions.index');
    Route::post('questions/store', 'QuestionsController@store')->name('questions.store');
    Route::delete('questions/destroy/{id}', 'QuestionsController@destroy')->name('questions.destroy');

    Route::get('reports/search-all', 'Admin\ReportsController@searchAll')->name('reports.index');
    Route::get('dl-file-destroy/{id?}/{file?}', 'DemandLiberariesController@dlFileDestroy')->name('reports.index');
});
Route::get('load-students/{id}', 'Admin\SchoolClassesController@loadStd');

Route::prefix('parent')->name('parent.')->middleware('checkAuth')->group(function() {
    Route::get('dashboard', 'Parent\ParentsController@dashboard');
    Route::get('children/{user_id?}', 'Parent\ParentsController@children');
    Route::get('children-create/{id?}', 'Parent\ParentsController@childCreate');
    Route::post('children/store/{user_id?}', 'Parent\ParentsController@childStore')->name('children.store');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::post('update-profile', 'Parent\ParentsController@updateProfile');
    Route::get('children-delete/{id}', 'Parent\ParentsController@deleteChild');
    Route::get('add-details/{id}', 'Parent\ParentsController@admissionDetails');
    Route::get('demand_library', 'Parent\ParentsController@demandLibrary');

    Route::get('stripesuccess', function () {
        return view('stripesuccess');
    });
    Route::post('stripepay', 'Parent\ParentsController@stripepay');
    Route::get('cancelsubscription/{id}', 'Parent\ParentsController@cancelstripesubscription');
});
Route::post('register-parent', 'Admin\UsersController@store');
Route::prefix('teacher')->name('teacher.')->middleware('checkAuth')->group(function() {
    Route::get('reports/search-all', 'Admin\ReportsController@searchAll')->name('reports.index');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::get('change-password', 'Admin\UsersController@changePassword');
});
Route::get('thanks', 'FrontendController@thanks');
Route::get('get-liberary-details/{id}', 'DemandLiberariesController@getDetail');

Route::get('demo', function () {
    return redirect('/page/schedule-a-demo');
});
Route::get('school-partnerships', function () {
    return redirect('/page/school-partnerships');
});
Route::get('enroll-your-school.html', function () {
    return redirect('/page/schedule-a-demo');
});

Route::get('enrichmentatschool.html', function () {
    return redirect('/page/classes');
});
Route::get('enroll-your-child.html', function () {

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model implements Auditable {

    use \OwenIt\Auditing\Auditable,
        SoftDeletes;

    protected $guarded = [];

    public function images() {
        return $this->hasMany(CategoryGallery::class)->orderBy('sort_order');
    }

    protected static function boot() {
        parent::boot();

        static::deleted(function ($invoice) {
            $invoice->images()->delete();
        });
    }

}

resources/views/admin/categories/create.blade.php
@extends('master')
@section('title','User Create')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <h4 class="semi-bold text-center light-heading">{{ __('Create Gallery') }}</h4>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('admin.categories.store') }}">
                        @include('admin.categories.form',['create'=>true])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('master')
@section('title','User Create')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <h4 class="semi-bold text-center light-heading">{{ __('Edit Section') }}</h4>

                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('admin.categories.update',$id) }}">
                        @method('put')
                        @include('admin.categories.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/form.blade.php
@csrf
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="row clearfix">
    <div class="col-md-6">
        <div class="form-group form-group-default required" aria-required="true">
            <label for="title" class="col-md-12 col-form-label text-md-left">Title</label>
            <input type="text" class="form-control " onchange="makeSlug(this.value)" name="category[title]" value="{{ $category->title }}" required="" autocomplete="off" autofocus="">
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group form-group-default required" aria-required="true">
            <label for="slug" class="col-md-12 col-form-label text-md-left">Slug</label>
            <input type="text" id="slug" class="form-control " name="category[slug]" value="{{ $category->slug }}" required="" autocomplete="off" autofocus="">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group form-group-default required" aria-required="true">
            <label for="title" class="col-md-12 col-form-label text-md-left">Description</label>
            <textarea style="height:100px !important;" class="section form-control" name="category[description]" required="" rows="5">{{ $category->description }}</textarea>

        </div>
    </div>
    <div class="col-lg-12">
        <label>Image</label>
        <br>
        <input type="file" class="dropify" data-default-file="{{ ($category->image)?asset('images/thumbnails/'.$category->image):'' }}" name="image" 
               @isset($create)
               required=""
               @endisset
               />
    </div>

</div>
<div class="form-group row mt-2">
    <div class="col-md-12 offset-md-12 text-right">
        <button id="save-form" type="submit" class="btn btn-primary">
            @isset($create)
            {{ __('Create') }}
            @else
            {{ __('Update') }}
            @endisset
        </button>
    </div>
</div>
<script type="text/javascript">
    function makeSlug($value) {
        var $slug = $value.toLowerCase().replace(' ', '-');
        $('#slug').val($slug);
    }
</script>

resources/views/admin/categories/index.blade.php
@extends('master')

@section('content')
<style>
    .editable-clear-x{
        display: none !important;
    }
    .form-control{
        padding:.6rem 1rem !important;
    }
    .table-responsive th,
    .table-responsive td {
        white-space: nowrap;
        border: 1px solid #ebedf2 !important;

    }
    .modal-lg{
        width: 1250px !important;
    }
</style>

<div class="d-flex">
            <h1 class="flex-grow-1 float-left">Gallery</h1>
            @can('gallery-edit')
            <a href="{{ route('admin.categories.create') }}" class="btn btn-success align-self-center" role="button">Create Gallery</a>
            @endcan
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row table-responsive">
                    @csrf
                    <table class="sortable table table-bordered draggable">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($banners as $k=>$b)
                            <tr>
                                <td>
                                    <?php
                                    if ($b->image && file_exists(public_path() . '/images/thumbnails/' . $b->image)) {
                                        $img = 'images/thumbnails/' . $b->image;
                                    } else {
                                        $img = 'avatar-2.png';
                                    }
                                    ?>
                                    <img class="preview" width="200px" src="<?= url($img); ?>">
                                </td>
                                <td>
                                    <?= $b->title ?>
                                </td>
                                <td>
                                    <?= $b->slug ?>
                                </td>
                                <td>
                                    <a href="{{ url('backend/change-status/categories/'.$b->id,$b->active) }}">

                                        <span class="span-status {{ $b->active == 1 ? 'active-span-bg': 'disabled-span-bg' }}">
                                            {{ $b->active == 1 ? __('Active') : __('Blocked') }}
                                        </span>
                                    </a>
                                </td>
                                <td class="sortable-handle">
                                    <a href="{{ route('admin.galleries',$b->id) }}" class="btn btn-warning">
                                        <i class="fa fa-info"></i>
                                    </a>
                                     @can('gallery-edit')
                                    <a href="{{ route('admin.categories.edit',$b->id) }}" class="btn btn-primary">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                     @endcan
                                      @can('gallery-delete')
                                    <button type="submit"
                                            onclick="event.preventDefault(); setUrl('{{ route('admin.category.destroy', $b->id) }}'); deleteConfirm('destroy', 'You are about to delete a banner, Are you sure?')"

                                            class="btn btn-icon btn-round btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                      @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <form 
                        id="destroy"
                        method="post" id="destroy" 
                        action="">
                        @csrf
                        @method('DELETE')
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@if(Session::has('outcome'))
<script>
    $(function () {
    $.toaster({priority: 'success', title: 'Success', message: "{{Session::get('outcome')}}"});
    })

</script>
@endif
<script type="text/javascript">
            function makeSlug($value){
//        alert($value);
            var $slug = $value.toLowerCase().replace(' ', '-');
            $('#slug').val($slug);
            }
    function setUrl($url){
    $('form#destroy').attr('action', $url);
    }
</script>
@endsection