routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

//Before authentication
Route::group(['middleware' => 'beforeAuth'], function() {
    Route::get('/', 'FrontendController@index');
//    Route::get('/', 'Admin\UsersController@login');
    Route::get('page/{type?}', 'FrontendController@index')->name('front');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');
    Route::get('view-service/{id}', 'FrontendController@service')->name('view-service');
    Route::get('service-detail/{id}', 'FrontendController@serviceDetails')->name('service-details');
    Route::get('privacy-policy', 'FooterController@privacy');
    Route::get('terms-conditions', 'FooterController@terms');

    Route::get('view-service-detail/{id}', 'FrontendController@serviceDetail')->name('view-service-detail');

    Route::post('dologin', 'Admin\UsersController@login');
    Route::post('send-message', 'FrontendController@sendMessage')->name('sendMessage');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');


//    Route::post('changePassword', 'Admin\UsersController@changePassword');
    Route::get('gallery/{slug}', 'FrontendController@gallery');
    Route::get('contact', 'FrontendController@contact');
    Route::get('find-your-school', 'FrontendController@findYourSchool');
    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    
    Route::get('frontend/school-details/{id}', 'FrontendController@schoolDetails');
    Route::get('frontend/class-details/{id}', 'FrontendController@classDetails');

    Route::get('parentlogin', 'FrontendController@login');
    Route::get('update-cart/{id?}', 'FrontendController@updateCart');
    Route::get('checkout', 'FrontendController@checkout');
    Route::post('store-order', 'FrontendController@storeOrder');
    Route::match(['get', 'post'], 'view-cart', 'FrontendController@viewCart');
    Route::get('forgotPassword', 'Admin\UsersController@recoverParentPassword');
    Route::get('resetPassword/{token}', 'Admin\UsersController@resetParentPassword');
});
Route::post('changePassword', 'Admin\UsersController@changePassword');


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function() {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list/{role_id?}', 'Admin\UsersController@index')->name('users.index');
    Route::match(['get', 'post'], '/parent-list/{role_id?}', 'Admin\UsersController@parentlist')->name('users.parentlist');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');


    //for home page banner
    // Route::resource('banners', 'BannerController')->except('show');

    Route::get('banners/{type?}', 'BannerController@index')->name('banners.index');
    Route::post('banners/store', 'BannerController@store')->name('banners.store');
    Route::delete('banners/destroy/{id}', 'BannerController@destroy')->name('banners.destroy');

    Route::post('bannar_ajax_upload', 'BannerController@bannar_ajax_upload')->name('bannar_ajax_upload');
    Route::post('banners/sort-order', 'BannerController@sortData')->name('banner.sort.order');
    Route::post('banners-upload', 'TrendingProductController@upload')->name('upload.widget.image');
    Route::get('change-status/{table}/{id}/{status}', 'BannerController@changeStatus')->name('admin.banner.change.status');

    Route::resource('pages', 'PagesController')->except('show');
    Route::get('page-details/{pageId}', 'PagesController@pageDetails')->name('page.details');
    Route::get('contact-details/{pageId}', 'PagesController@contactDetails')->name('contact.details');
    Route::get('pages/edit/{id?}', 'PagesController@index');
    Route::get('page-details/create/{pageId}', 'PagesController@pageDetailCreate')->name('page.details.create');
    Route::post('page-details/store/{pageId}', 'PagesController@pageDetailStore')->name('page.details.store');
    Route::get('page-details/edit/{id}', 'PagesController@pageDetailEdit')->name('page.details.edit');
    Route::put('page-details/update/{id}', 'PagesController@pageDetailUpdate')->name('page.details.update');

    Route::post('categories/store', 'GalleriesController@categoriesStore')->name('categories.store');
    Route::get('categories', 'GalleriesController@categories')->name('categories.index');
    Route::get('categories/edit/{id}', 'GalleriesController@categoriesEdit')->name('categories.edit');
    Route::get('categories/create', 'GalleriesController@categoriesCreate')->name('categories.create');
    Route::put('categories/update/{id}', 'GalleriesController@categoriesUpdate')->name('categories.update');

    Route::get('demand-liberaries', 'DemandLiberariesController@index')->name('demand_liberaries.index');
    Route::get('demand-liberaries/create', 'DemandLiberariesController@create')->name('demand_liberaries.create');
    Route::post('demand-liberaries/store', 'DemandLiberariesController@store')->name('demand_liberaries.store');
    Route::get('demand-liberaries/edit/{id}', 'DemandLiberariesController@edit')->name('demand_liberaries.edit');
    Route::put('demand-liberaries/update/{id}', 'DemandLiberariesController@update')->name('demand_liberaries.update');
    Route::delete('demand-liberaries/destroy/{id}', 'DemandLiberariesController@destroy')->name('demand.destroy');
    

    Route::get('galleries/{id}', 'GalleriesController@index')->name('galleries');
    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');
    Route::delete('galleries/destroy/{id}', 'GalleriesController@destroy')->name('galleries.destroy');
    Route::post('ck-editor/uploads', 'BannerController@ckeditorUpload')->name('ckeditor.upload');

    Route::delete('category/destroy/{id}', 'GalleriesController@destroyCategory')->name('category.destroy');
    Route::delete('page_details/destroy/{id}', 'PagesController@pageDetailDestroy')->name('page_details.destroy');
//    Route::post('galleries/store/{id}', 'GalleriesController@store')->name('gelleries.store');

    Route::get('contacts', 'PagesController@contacts');
    Route::delete('contacts/destroy/{id}', 'PagesController@ContactsDestroy')->name('contact.destroy');

    Route::post('pages/updatetype', 'PagesController@updateType')->name('pages.updatetype');
    Route::get('services/{type?}', 'ServicesController@index')->name('services.index');
    Route::post('services/store', 'ServicesController@store')->name('services.store');
    Route::delete('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');

    Route::resource('testimonials', 'TestimonialController');
    Route::resource('teams', 'TeamController');

    Route::resource('footers', 'FooterController');

    Route::match(['get', 'post'], 'states', 'Admin\StatesController@index');
    Route::get('states/create/{id?}', 'Admin\StatesController@create');
    Route::post('states/store', 'Admin\StatesController@store')->name('states.store');
    Route::delete('states-destroy/{id}', 'Admin\StatesController@destroy')->name('states.destroy');

    Route::match(['get', 'post'], 'cities/{state_id}', 'Admin\CitiesController@index');
    Route::get('cities-create/{state_code}/{id?}', 'Admin\CitiesController@create');
    Route::post('cities-store', 'Admin\CitiesController@store')->name('cities.store');
    Route::delete('cities-destroy/{id}', 'Admin\CitiesController@destroy')->name('cities.destroy');



    Route::match(['get', 'post'], 'schools', 'Admin\SchoolsController@index');
    Route::get('schools-create/{id?}', 'Admin\SchoolsController@create');
    Route::post('schools-store', 'Admin\SchoolsController@store')->name('schools.store');
    Route::delete('schools-destroy/{id}', 'Admin\SchoolsController@destroy')->name('schools.destroy');


    Route::get('cities-dd', 'Admin\SchoolsController@citiesDD');
    Route::get('class-dd', 'AdmissionsController@classDD')->name('class-dd');
    Route::get('child-dd', 'AdmissionsController@childDD')->name('child-dd');


    Route::match(['get', 'post'], 'school-classes/{id}', 'Admin\SchoolClassesController@index');
    Route::get('school-classes-create/{school_id}/{class_id?}', 'Admin\SchoolClassesController@create');
    Route::post('school-classes-store', 'Admin\SchoolClassesController@store')->name('school.classes.store');
    Route::delete('schools-classes-destroy/{id}', 'Admin\SchoolClassesController@destroy')->name('schools.classes.destroy');


    Route::get('admissions', 'AdmissionsController@index');

resources/views/pages/contacts.blade.php
@extends('master')

@section('content')
<style>
    .editable-clear-x{
        display: none !important;
    }
    .form-control{
        padding:.6rem 1rem !important;
    }
    .table-responsive th,
    .table-responsive td {
        white-space: nowrap;
        border: 1px solid #ebedf2 !important;
    }
    .modal-lg{
        width: 1250px !important;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div class="d-flex">
            <h1 class="flex-grow-1 float-left">Contacts</h1>
        </div>
        <div class="card">

            <div class="card-body">
                <div class="row table-responsive">
                    @csrf
                    <table class="sortable table table-bordered draggable">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Message</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($contacts as $k=>$b)
                            <tr>
                                <td>
                                    <?= $b->first_name ?>
                                </td>
                                <td>
                                    <?= $b->last_name ?>
                                </td>
                                <td>
                                    <?= $b->email ?>
                                </td>
                                <td>
                                    <?= $b->phone ?>
                                </td>
                                <td>
                                    <?= $b->message ?>
                                </td>
                                <td class="sortable-handle">
                                  @can('setting-delete')
                                    <button type="submit"
                                            onclick="event.preventDefault(); setUrl('{{ route('admin.contact.destroy', $b->id) }}'); deleteConfirm('destroy', 'Associated data with this page will also be deleted, Are you sure?')"

                                            class="btn btn-icon btn-round btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                  @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="mt-2">
                    {{ $contacts->links() }}
                        
                    </div>
                    <form 
                        id="destroy"
                        method="post" id="destroy" 
                        action="">
                        @csrf
                        @method('DELETE')
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@if(Session::has('outcome'))
<script>
    $(function () {
    $.toaster({priority: 'success', title: 'Success', message: "{{Session::get('outcome')}}"});
    })

</script>
@endif
<script type="text/javascript">
            function makeSlug($value){
//        alert($value);
            var $slug = $value.toLowerCase().replace(' ', '-');
            $('#slug').val($slug);
            }
    function setUrl($url){
    $('form#destroy').attr('action', $url);
    }
</script>
@endsection

resources/views/pages/edit.blade.php
@extends('master')

@section('content')
<style>
    .editable-clear-x{
        display: none !important;
    }
    .form-control{
        padding:.6rem 1rem !important;
    }
    .table-responsive th,
    .table-responsive td {
        white-space: nowrap;
        border: 1px solid #ebedf2 !important;
    }
    .modal-lg{
        width: 1250px !important;
    }
</style>
{{--@can('banner.index', 'update')--}}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title pull-left">{{ __('Edit Page') }}</div>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.pages.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>Title</label>
                            <input type="hidden" value="{{ $page->id }}" name="id"/>
                            <input type="text" onchange="makeSlug(this.value)" value="{{ $page->title }}" class="form-control" name="page[title]"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>Slug</label>
                            <input type="text" class="form-control" value="{{ $page->slug }}" id="slug" name="page[slug]"/>
                        </div>
                        
                         <div class="col-lg-12 col-md-6 col-sm-12 col-12">
                            <label>Page Keyword</label>
                            <input type="text" class="form-control" value="{{$page->meta_keyword}}" id="keyword" name="page[meta_keyword]"/>
                        </div>
                        <div class="col-lg-12 col-md-6 col-sm-12 col-12">
                            <label>Page Description</label>
                            <textarea class="form-control" id="description" name="page[meta_description]">{{$page->meta_description}}</textarea>
                        </div>
                    </div>
                    <div class="row">
                    </div>
                    <button type="submit" class="mt-2 pull-right btn btn-success">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{{--@endcan--}}

@endsection
@section('script')
@if(Session::has('outcome'))
<script>
    $(function () {
    $.toaster({priority: 'success', title: 'Success', message: "{{Session::get('outcome')}}"});
    })

</script>
@endif
<script type="text/javascript">
            function makeSlug($value){
            var $slug = $value.trim().toLowerCase().replaceAll(' ', '-');
            $('#slug').val($slug);
            }
             function setUrl($url){
        $('form#destroy').attr('action',$url);
    }
</script>
@endsection

resources/views/pages/index.blade.php
@extends('master')

@section('content')
<style>
    .editable-clear-x{
        display: none !important;
    }
    .form-control{
        padding:.6rem 1rem !important;
    }
    .table-responsive th,
    .table-responsive td {
        white-space: nowrap;
        border: 1px solid #ebedf2 !important;
    }
    .modal-lg{
        width: 1250px !important;
    }
</style>
@can('page-edit')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title pull-left">{{ __('Create New Page') }}</div>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.pages.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <label class="col-12 mb-2">Header Type</label>
                            <label>
                                <input type="radio" value="main header" name="page[header_type]"/>
                                Main Header
                            </label>
                            <label>
                                <input type="radio" value="upper header" name="page[header_type]"/>
                                Upper Header
                            </label>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>Title</label>
                            <input type="text" onchange="makeSlug(this.value)" class="form-control" name="page[title]"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                            <label>Slug</label>
                            <input type="text" class="form-control" id="slug" name="page[slug]"/>
                        </div>
                        <div class="col-lg-12 col-md-6 col-sm-12 col-12">
                            <label>Page Keyword</label>
                            <input type="text" class="form-control" id="keyword" name="page[meta_keyword]"/>
                        </div>
                        <div class="col-lg-12 col-md-6 col-sm-12 col-12">
                            <label>Page Description</label>
                            <textarea class="form-control" id="description" name="page[meta_description]"></textarea>
                        </div>
                    </div>
                    <div class="row">
                    </div>
                    <button type="submit" class="mt-2 pull-right btn btn-success">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endcan

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title pull-left">{{ __('Pages') }}</div>
            </div>
            <div class="card-body">
                <div class="row table-responsive">

                    <form action="{{ route('admin.pages.updatetype') }}" method="POST">
                        @csrf
                        <table class="sortable table table-bordered draggable">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Slug</th>
                                    <th>Header Type</th>
                                    <th>Status</th>
                                    <th>Is Front Page</th>
                                    <th>Is Contact</th>
                                    <th>Is Service</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($banners as $k=>$b)
                                <tr>
                                    <td>
                                        <?= $b->title ?>
                                    </td>
                                    <td>
                                        <?= $b->slug ?>
                                    </td>
                                    <td>
                                        <?= ucwords($b->header_type) ?>
                                    </td>
                                    <td>
                                        <a href="{{ url('backend/change-status/pages/'.$b->id,$b->active) }}">

                                            <span class="span-status {{ $b->active == 1 ? 'active-span-bg': 'disabled-span-bg' }}">
                                                {{ $b->active == 1 ? __('Active') : __('Blocked') }}
                                            </span>
                                        </a>
                                    </td>
                                    <td>
                                        @if($b->is_front == 0)
                                        @php
                                        $value = 0;
                                        $checked = "";
                                        @endphp
                                        @else    
                                        @php
                                        $value = 1;
                                        $checked = "checked='checked'";
                                        @endphp
                                        @endif
                                        <input type="hidden"  name="pageid_front[]" value="{{$b->id}}" />
                                        <input type="hidden"  name="is_front_radio[]" value="{{$b->is_front}}" id="frontradio-{{$b->id}}" class="allFrontVal" />
                                        <input type="radio"  name="is_front[]" value="{{$b->is_front}}" {{$checked}} class="frontradio-{{$b->id}}" onChange="setFrontVal(this)" />
                                    </td>
                                    <td>
                                        @if($b->is_contact == 0)
                                        @php
                                        $value = 0;
                                        $checked = "";
                                        @endphp
                                        @else    
                                        @php
                                        $value = 1;
                                        $checked = "checked='checked'";
                                        @endphp
                                        @endif
                                        <input type="hidden"  name="pageid_contact[]" value="{{$b->id}}" />
                                        <input type="hidden"  name="is_contact_radio[]" value="{{$b->is_contact}}" id="contactradio-{{$b->id}}" class="allContactVal" />
                                        <input type="radio"  name="is_contact[]" value="{{$b->is_contact}}" {{$checked}} class="contactradio-{{$b->id}}" onChange="setContactVal(this)" />
                                    </td>
                                    <td>
                                        @if($b->is_service == 0)
                                        @php
                                        $value = 0;
                                        $checked = "";
                                        @endphp
                                        @else    
                                        @php
                                        $value = 1;
                                        $checked = "checked='checked'";
                                        @endphp
                                        @endif
                                        <input type="hidden"  name="pageid_service[]" value="{{$b->id}}" />
                                        <input type="hidden"  name="is_service_radio[]" value="{{$b->is_service}}" id="serviceradio-{{$b->id}}" class="service-values" />
                                        <input type="radio"  name="is_service[]" value="{{$b->is_service}}" {{$checked}} class="serviceradio-{{$b->id}}" onChange="setServiceVal(this)" />
                                    </td>
                                    <td class="sortable-handle">
                                        @if($b->is_contact == 1)
                                        @can('setting.edit')
                                        <a href="{{ route('admin.contact.details',$b->id) }}" class="btn btn-primary">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        @endcan
                                        @elseif($b->is_service == 1)
                                        <a href="{{ route('admin.services.index') }}" class="btn btn-warning">
                                            <i class="fa fa-info"></i>
                                        </a>
                                        @else
                                        <a href="{{ route('admin.page.details',$b->id) }}" class="btn btn-warning">
                                            <i class="fa fa-info"></i>
                                        </a>

                                        @endif
                                        @can('page-edit')
                                        @if($b->is_service != 1 && $b->is_contact !=1)
                                        <a href="{{ url('backend/pages/edit/'.$b->id) }}" class="btn btn-primary">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        @endif
                                        @endcan

                                        @can('page-delete')
                                        <button type="submit"
                                                onclick="event.preventDefault(); setUrl('{{ route('admin.pages.destroy', $b->id) }}'); deleteConfirm('destroy', 'Associated data with this page will also be deleted, Are you sure?')"

                                                class="btn btn-icon btn-round btn-danger">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        @endcan
                                    </td>
                                </tr>
                                @endforeach
                                @can('page.edit')
                                <tr>

                                    <td colspan="6">
                                        <input type="submit" value="Update" class="btn btn-success m-auto d-block"/>
                                    </td>

                                </tr>    
                                @endcan
                            </tbody>
                        </table>
                    </form>
                    <form 
                        id="destroy"
                        method="post" id="destroy" 
                        action="">
                        @csrf
                        @method('DELETE')
                    </form>
<div class="mt-2">
                    {{ $banners->links() }}
                        
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@if(Session::has('outcome'))
<script>
    $(function () {
    $.toaster({priority: 'success', title: 'Success', message: "{{Session::get('outcome')}}"});
    })

</script>
@endif
<script type="text/javascript">
            function makeSlug($value){
            var $slug = $value.trim().toLowerCase().replaceAll(' ', '-');
            $('#slug').val($slug);
            }
    function setUrl($url){
    $('form#destroy').attr('action', $url);
    }
    function setFrontVal(e) {
    $(".allFrontVal").attr('value', '0');
    $("#" + e.className).attr('value', '1');
    }
    function setContactVal(e) {
    $(".allContactVal").attr('value', '0');
    $("#" + e.className).attr('value', '1');
    }
    function setServiceVal(e) {

    $(".service-values").attr('value', '0');
    $("#" + e.className).attr('value', '1');
    }
</script>
@endsection